name: CI

on:
  push: {}

env:
  SYMBOLIZE_DEPS: libunwind-dev binutils-dev
  BAZEL_SYMBOLIZE_FLAGS: >-
    --copt=-DHAVE_SYMBOLIZE
    --copt=-DHAVE_UNWIND
    --copt=-DHAVE_LIBUNWIND
    --linkopt=-lunwind
    --linkopt=-ldl

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-setup

    - name: Build
      run: |
        bazel build //... \
          ${{ env.BAZEL_SYMBOLIZE_FLAGS }}

    - name: Test
      run: |
        bazel test //... --test_output=errors \
          ${{ env.BAZEL_SYMBOLIZE_FLAGS }}

  build_and_test_asan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/ci-setup

    - name: Build with address sanitizer
      run: |
        bazel build --config=asan //... \
          ${{ env.BAZEL_SYMBOLIZE_FLAGS }}

    - name: Test with address sanitizer
      run: |
        bazel test --config=asan //... --test_output=errors \
          ${{ env.BAZEL_SYMBOLIZE_FLAGS }}
