name: CI

on:
  push: {}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get clean

    - uses: bazel-contrib/setup-bazel@0.15.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per job to avoid concurrent writes.
        disk-cache: ${{ github.workflow }}-${{ github.job }}
        # Share repository cache between workflows.
        repository-cache: true

    - name: Build
      run: |
        bazel build //...

    - name: Test
      run: |
        bazel test //... --test_output=errors

  build_and_test_asan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo apt-get clean

    - uses: bazel-contrib/setup-bazel@0.15.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per job to avoid concurrent writes.
        disk-cache: ${{ github.workflow }}-${{ github.job }}
        # Share repository cache between workflows.
        repository-cache: true

    - name: Build with address sanitizer
      run: |
        bazel build --config=asan //...

    - name: Test with address sanitizer
      run: |
        bazel test --config=asan //... --test_output=errors
